#!/bin/bash
# Author: Austin Cunningham
# Student Number: 20073379
# Version: 22/10/2016

clear
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
echo
echo -e ${YELLOW} ____________________________________________________________ ${NONE}
echo -e " ${YELLOW}       _          _       _     ____               ${NONE}"
echo -e " ${YELLOW}      / \      __| |   __| |   |  _ \    ___   _ __ ___      ${NONE}"
echo -e " ${YELLOW}     / _ \    / _  |  / _  |   | |_) |  / _ \ |  _   _ \       ${NONE}"
echo -e " ${YELLOW}    / ___ \  | (_| | | (_| |   |  __/  |  __/ | | | | | |           ${NONE}"
echo -e " ${YELLOW}   /_/   \_\  \__,_|  \__,_|   |_|      \___| |_| |_| |_|           ${NONE}"
echo -e ${YELLOW} ____________________________________________________________ ${NONE}
echo -e ${YELLOW} ____________________________________________________________ ${NONE}



