#!/bin/bash
# Author: Austin Cunningham
# Student Number: 20073379
# Version: 22/10/2016

clear
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
echo
echo -e ${CYAN} ____________________________________________________________ ${NONE}
echo -e " ${CYAN}  ____              ____            _       _    ${NONE}"
echo -e " ${CYAN} |  _ \ _   _ _ __ / ___|  ___ _ __(_)_ __ | |_    ${NONE}"
echo -e " ${CYAN} | |_) | | | |  _  \___ \ / __|  __| |  _ \| __|   ${NONE}"
echo -e " ${CYAN} |  _ <| |_| | | | |___) | (__| |  | | |_) | |_             ${NONE}"
echo -e " ${CYAN} |_| \\_\\\__,__|_| |_|____/ \\___|_|  |_| .__/ \\__| ${NONE}"
echo -e " ${CYAN}                                     |_|           ${NONE}"
echo -e ${CYAN} ____________________________________________________________ ${NONE}
echo -e ${CYAN} ____________________________________________________________ ${NONE}









