#!/bin/bash
# Author: Austin Cunningham
# Student Number: 20073379
# Version: 22/10/2016

clear
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
echo
echo -e ${RED} ____________________________________________________________ ${NONE}
echo -e " ${RED}       ____                       _ _           ${NONE}"
echo -e " ${RED}      / ___|  ___  ___ _   _ _ __(_) |_ _   _  ${NONE}"
echo -e " ${RED}      \___ \ / _ \/ __| | | | '__| | __| | | |     ${NONE}"
echo -e " ${RED}       ___) |  __/ (__| |_| | |  | | |_| |_| |  ${NONE}"
echo -e " ${RED}      |____/ \___|\___|\__,_|_|  |_|\__|\__, |     ${NONE}"
echo -e " ${RED}                                        |___/           ${NONE}"
echo -e ${RED} ____________________________________________________________ ${NONE}
echo -e ${RED} ____________________________________________________________ ${NONE}















