#!/bin/bash
# Author: Austin Cunningham
# Student Number: 20073379
# Version: 22/10/2016

clear
NONE='\033[00m'
RED='\033[01;31m'
GREEN='\033[01;32m'
YELLOW='\033[01;33m'
BLUE='\033[01;34m'
PURPLE='\033[01;35m'
CYAN='\033[01;36m'
WHITE='\033[01;37m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
echo
echo -e ${BLUE} ____________________________________________________________ ${NONE}
echo -e " ${BLUE}   ____  _                ___        ______   ${NONE}"
echo -e " ${BLUE}  / ___|| |_ ___  _ __   / \ \      / / ___|   ${NONE}"
echo -e " ${BLUE}  \___ \| __/ _ \| '_ \ / _ \ \ /\ / /\___ \  ${NONE}"
echo -e " ${BLUE}   ___) | || (_) | |_) / ___ \ V  V /  ___) |           ${NONE}"
echo -e " ${BLUE}  |____/ \__\___/| .__/_/   \_\_/\_/  |____/            ${NONE}"
echo -e " ${BLUE}                 |_|                                  ${NONE}"
echo -e ${BLUE} ____________________________________________________________ ${NONE}
echo -e ${BLUE} ____________________________________________________________ ${NONE}







